exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "block_administrator.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: no-commit-to-branch
        args: ['--branch', 'develop']
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
        exclude: ^block_administrator/tests/classes/context_managers\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                block_administrator/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                block_administrator/www/website_script.js|
                block_administrator/templates/includes/.*|
                block_administrator/public/js/lib/.*|
                block_administrator/website/doctype/website_theme/website_theme_template.scss
            )$


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.23.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                block_administrator/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                block_administrator/www/website_script.js|
                block_administrator/templates/includes/.*|
                block_administrator/public/js/lib/.*
            )$

  - repo: local
    hooks:
      - id: clone-local-repo
        name: clone-local-repo
        entry: bash -c 'TARGET_DIR=".frappe-semgrep" && [ ! -d "$TARGET_DIR" ] && git clone "https://github.com/frappe/semgrep-rules" "$TARGET_DIR" || true'
        language: system
        always_run: true

  - repo: https://github.com/semgrep/pre-commit
    rev: "v1.91.0"
    hooks:
      - id: semgrep-ci
        args:
          [
            "--config",
            "./.frappe-semgrep/rules",
            "--config",
            "r/python.lang.correctness",
            "--error",
            "--skip-unknown-extensions",
            "--metrics",
            "off",
          ]

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false